# Generated by Django 3.2.8 on 2021-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='cont_phone',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='count_name',
        ),
        migrations.AddField(
            model_name='detail',
            name='car_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='customer_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='service_cat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
